### ISSUE TITLE
Webserver breaks against big changes

### ISSUE THREAD

**Issue by MarcoLPR** [unosquare/embedio-cli#7]
If I save a large amount of code running the server, it shows an error and finishes the process.

``
08:32:28.913 ERR >> [HttpHandler] No module generated a response. Sending 404 - Not Found
 08:36:27.655 ERR >> [HttpHandler] No module generated a response. Sending 404 - Not Found
 08:36:52.322 ERR >> [HttpHandler] No module generated a response. Sending 404 - Not Found

 08:37:18.875 ERR >> [WebSocketsServer] The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseReceived'
    $type           : System.Net.WebSockets.WebSocketException
    ErrorCode       : 0
    WebSocketErrorCode: object
        $type           : System.Net.WebSockets.WebSocketError
        value__         : 0
    NativeErrorCode : 0
    Message         :
        The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseReceived'
    TargetSite      :
        Void ThrowOnInvalidState(System.Net.WebSockets.WebSocketState, System.Net.WebSockets.WebSocketState[])
    StackTrace      :
        at System.Net.WebSockets.WebSocket.ThrowOnInvalidState(WebSocketState sUnhandled Exception: tate, WebSocketState[] validStates)
        at System.Net.WebSockets.WebSocketBase.SendAsyncCore(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
        at Unosquare.Labs.EmbedIO.Modules.WebSocketsServer.Send(IWebSocketContext webSocket, String payload)
    Source          : System.Net.WebSockets
    HResult         : -2147467259
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Unosquare.Labs.EmbedIO.Modules.WebSocketsServer.Broadcast(String payload)
   at Unosquare.Labs.EmbedIO.Command.WebSocketsWatcherServer.<.ctor>b__0_0(Object s, Object e) in C:\Unosquare\embedio-cli\src\embedio-cli\WebSocket.cs:line 28
   at Unosquare.Labs.EmbedIO.Command.Watcher.OnChanged(Object source, FileSystemEventArgs e) in C:\Unosquare\embedio-cli\src\embedio-cli\Watcher.cs:line 33
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, String name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
``
>

**Comment by geoperez** [comment]
We need to rewrite this tool. The current version is not compatible with EmbedIO v3.
